version: '3'
services:
  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=anomaly_test
  postgres:
    image: "postgres:11.1"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=anomaly_test