package statement

const (
	ReadUncommitted = "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED"
	ReadCommitted   = "SET TRANSACTION ISOLATION LEVEL READ COMMITTED"
	RepeatableRead  = "SET TRANSACTION ISOLATION LEVEL REPEATABLE READ"
	Serializable    = "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE"
)
